### ISSUE TITLE
FAKE.exe missing

### ISSUE THREAD

**Issue by TysonMN** [elmish/sample-react-navigation#10]
When I tried to build, I get an error because `./packages/build/FAKE/tools/FAKE.exe` is missing.

Am I doing something wrong?

**Comment by et1975** [comment]
The tooling needs to be updated, but if you use the shell scripts it should work.

**Comment by TysonMN** [comment]
Could you elborate a bit?

I tried to follow the instructions in `README.md`, but the link in
> For more information about it see [the docs](https://fable-elmish.github.io/browser).

is broken and executing `build Watch` does nothing.

I got the above build error by executing `sh build.sh`.

**Comment by et1975** [comment]
just looked at it again, it needs update to at least this kinda tooling: https://github.com/elmish/sample-react-counter, but ideally, everything from elmish onward would be converted to use FAKE5 as `dotnet` extension. `paket` is also no longer necessary, so could drop that too. And I'm not installing mono on machines anymore.

**Comment by TysonMN** [comment]
Exeucting `build Watch` in https://github.com/elmish/sample-react-counter produces the `FAKE.exe` file that is missing for me here, but then it runs into another problem https://github.com/elmish/sample-react-counter/issues/8.

I am not familiar with this tooling, so I don't see what the difference is.

**Comment by TysonMN** [comment]
I would update the tooling if I knew how.  Would be possible to give me some direction on how I could make this happen?

**Comment by et1975** [comment]
Updated the tooling and published a fresh sample.

**Comment by TysonMN** [comment]
Thanks @et1975.  The directions seemed much clearer to me this time.

I only had one other issue, which was that my version of node was too old.  After I upgraded from version 8.11.3 to version 12.18.0 (the latest LTS release), everything worked.

Thanks again :)
